routes/web.php
<?php

use App\Http\Controllers\FormController;
use App\Http\Controllers\FormValueController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SocialLoginController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test-mail', [SettingsController::class, 'testMail'])->name('test.mail')->middleware(['auth', 'xss']);
Auth::routes();

Route::group(['middleware' => ['auth', 'xss']], function () {
    Route::resource('profile', \App\Http\Controllers\ProfileController::class);
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('permission', \App\Http\Controllers\PermissionController::class);
    Route::resource('roles', \App\Http\Controllers\RoleController::class);
    Route::resource('module', \App\Http\Controllers\ModuleController::class);
    Route::resource('formvalues', \App\Http\Controllers\FormValueController::class);
});
Route::resource('forms', \App\Http\Controllers\FormController::class)->middleware(['auth', 'xss']);

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware(['auth', 'xss']);
Route::post('/chart', [HomeController::class, 'formchart'])->name('get.chart.data')->middleware(['auth', 'xss']);

Route::get('/invisible', fn () => view('invisible'));
Route::post('/invisible', function (Request $request) {
    $request->validate([
        'g-recaptcha-response' => 'required|captcha',
    ]);

    return 'Data is valid';
});

Route::get('/form-values/{id}/download/pdf', ['as' => 'download.form.values.pdf', 'uses' => '\App\Http\Controllers\FormValueController@download_pdf'])->middleware(['auth', 'xss']);

Route::get('update-avatar/{id}', [
    'as' => 'update-avatar',
    'uses' => '\App\Http\Controllers\ProfileController@showAvatar',
])->middleware(['auth', 'xss']);

Route::get('design/{id}', [
    'as' => 'forms.design',
    'uses' => '\App\Http\Controllers\FormController@design',
])->middleware(['auth', 'xss']);
// Route::get('test_design/{id}', [
//     'as' => 'forms.design',
//     'uses' => '\App\Http\Controllers\FormController@designtest'
// ])->middleware(['auth', 'xss']);
Route::put('/forms/design/{id}', ['as' => 'forms.design.update', 'uses' => '\App\Http\Controllers\FormController@designUpdate'])->middleware(['auth', 'xss']);

Route::post('update-avatar/{id}', '\App\Http\Controllers\ProfileController@updateAvatar');

Route::post('update-profile-login/{id}', [
    'uses' => '\App\Http\Controllers\ProfileController@updateLogin',
    'as' => 'update-login',
]);
Route::get('account-status/{id}', '\App\Http\Controllers\UserController@accountStatus')->name('account.status');
Route::get('profile-status', '\App\Http\Controllers\ProfileController@profileStatus')->name('profile.status');

Route::get('/forms/fill/{id}', ['as' => 'forms.fill', 'uses' => '\App\Http\Controllers\FormController@fill'])->middleware(['auth', 'xss']);
Route::get('/forms/survey/{id}', ['as' => 'forms.survey', 'uses' => '\App\Http\Controllers\FormController@publicFill'])->middleware(['xss']);
Route::put('/forms/fill/{id}', ['as' => 'forms.fill.store', 'uses' => '\App\Http\Controllers\FormController@fillStore'])->middleware(['xss']);
Route::get('/form-values/{id}/edit', ['as' => 'edit.form.values', 'uses' => '\App\Http\Controllers\FormValueController@edit'])->middleware(['auth', 'xss']);
Route::get('/form-values/{id}/view', ['as' => 'view.form.values', 'uses' => '\App\Http\Controllers\FormValueController@showSubmitedForms'])->middleware(['auth', 'xss']);
Route::post('/form-duplicate', ['as' => 'forms.duplicate', 'uses' => '\App\Http\Controllers\FormController@duplicate'])->middleware(['auth', 'xss']);
Route::get('/form-values/{id}/download/csv2', ['as' => 'download.form.values.csv2', 'uses' => '\App\Http\Controllers\FormValueController@download_csv_2'])->middleware(['auth', 'xss']);

Route::post('/mass/export/xlsx', ['as' => 'mass.export.xlsx', 'uses' => '\App\Http\Controllers\FormValueController@export_xlsx'])->middleware(['auth', 'xss']);
Route::post('/mass/export/csv', ['as' => 'mass.export.csv', 'uses' => '\App\Http\Controllers\FormValueController@export'])->middleware(['auth', 'xss']);

Route::post('ckeditors/upload', [FormController::class, 'ckupload'])->name('ckeditors.upload')->middleware('auth');

Route::resource('role', \App\Http\Controllers\RoleController::class);
Route::post('/role-permission/{id}', [
    'as' => 'roles_permit',
    'uses' => '\App\Http\Controllers\RoleController@assignPermission',
]);

Route::get('/settings', [SettingsController::class, 'index'])->name('settings')->middleware(['auth', 'xss']);

Route::post('settings/app-name/update', [
    'as' => 'settings/app-name/update',
    'uses' => '\App\Http\Controllers\SettingsController@appNameUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/app-logo/update', [
    'as' => 'settings/app-logo/update',
    'uses' => '\App\Http\Controllers\SettingsController@appLogoUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/pusher-setting/update', [
    'as' => 'settings/pusher-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@pusherSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/wasabi-setting/update', [
    'as' => 'settings/wasabi-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@wasabiSettingUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/captcha-setting/update', [
    'as' => 'settings/captcha-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@captchaSettingUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/stripe-setting/update', [SettingsController::class, 'paymentSettingUpdate'])->name('settings/stripe-setting/update');
Route::post('settings/social-setting/update', [SettingsController::class, 'socialSettingUpdate'])->name('settings/social-setting/update');

Route::get('/redirect/{provider}', [SocialLoginController::class, 'redirect']);
Route::get('/callback/{provider}', [SocialLoginController::class, 'callback'])->name('social.callback');

Route::post('filter-chart/{id}', [FormValueController::class, 'getGraphData'])->name('filter_chart')->middleware(['auth', 'xss']);

Route::post('settings/email-setting/update', [
    'as' => 'settings/email-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@emailSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/auth-settings/update', [
    'as' => 'settings/auth-settings/update',
    'uses' => '\App\Http\Controllers\SettingsController@authSettingsUpdate',
])->middleware(['auth', 'xss']);

Route::post('test-mail', '\App\Http\Controllers\SettingsController@testSendMail')->name('test.send.mail')->middleware(['auth', 'xss']);
Route::post('/verify-2fa', [
    'as' => 'verify-2fa',
    'uses' => '\App\Http\Controllers\ProfileController@verify',
]);

Route::post('/activate-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@activate',
    'as' => 'activate-2fa',
]);

Route::post('/enable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@enable',
    'as' => 'enable-2fa',
]);

Route::post('/disable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@disable',
    'as' => 'disable-2fa',
]);

Route::get('/2fa/instruction', [
    'uses' => '\App\Http\Controllers\ProfileController@instruction',
]);

Route::post('/2fa', fn () => redirect()->to(URL()->previous()))->name('2fa')->middleware('2fa');

Route::group(['prefix' => '2fa'], function () {
    Route::get('/', '\App\Http\Controllers\LoginSecurityController@show2faForm');
    Route::post('/generateSecret', '\App\Http\Controllers\LoginSecurityController@generate2faSecret')->name('generate2faSecret');
    Route::post('/enable2fa', '\App\Http\Controllers\LoginSecurityController@enable2fa')->name('enable2fa');
    Route::post('/disable2fa', '\App\Http\Controllers\LoginSecurityController@disable2fa')->name('disable2fa');

    Route::post('/2faVerify', fn () => redirect()->to(URL()->previous()))->name('2faVerify')->middleware('2fa');
});

Route::get('/test_middleware', fn () => '2FA middleware work!')->middleware(['auth', '2fa']);

Route::any('(:any)/(:all?)', function ($first, $rest = '') {
    $page = $rest ? "{$first}/{$rest}" : $first;
    dd($page);
});

Route::get('setting/{id}', [
    'as' => 'setting',
    'uses' => '\App\Http\Controllers\SettingsController@loadsetting',
])->middleware(['auth', 'xss']);

Route::post('ckeditor/upload', '\App\Http\Controllers\FormController@upload')->name('ckeditor.upload');
Route::group(
    ['middleware' => ['auth', 'xss']],
    function () {
        Route::get('change-language/{lang}', '\App\Http\Controllers\LanguageController@changeLanquage')->name('change.language');
        Route::get('manage-language/{lang}', '\App\Http\Controllers\LanguageController@manageLanguage')->name('manage.language');
        Route::post('store-language-data/{lang}', '\App\Http\Controllers\LanguageController@storeLanguageData')->name('store.language.data');
        Route::get('create-language', '\App\Http\Controllers\LanguageController@createLanguage')->name('create.language');
        Route::post('store-language', '\App\Http\Controllers\LanguageController@storeLanguage')->name('store.language');
        Route::delete('/lang/{lang}', '\App\Http\Controllers\LanguageController@destroyLang')->name('lang.destroy');
    }
);

resources/views/form/action.blade.php
@can('edit-form')
    @if ($form->json)
        @php
            $hashids = new Hashids('', 20);
            $id = $hashids->encodeHex($form->id);
        @endphp
        <a class="btn  btn-sm small btn-primary embed_form" href="javascript:void(0)" title="{{ __('Embed form') }}"
            onclick="copyToClipboard('#embed-form-{{ $form->id }}')" id="embed-form-{{ $form->id }}"
            data-url='<iframe src="{{ route('forms.survey', $id) }}" scrolling="auto" align="bottom" style="height:100vh;" width="100%"></iframe>'><i
                class="ti ti-code"></i></a>
        <a class="btn  btn-primary btn-sm small copy_form" onclick="copyToClipboard('#copy-form-{{ $form->id }}')"
            href="javascript:void(0)" title="{{ __('Copy Form URL') }}" id="copy-form-{{ $form->id }}"
            data-url="{{ route('forms.survey', $id) }}"><i class="ti ti-copy"></i></a>
    @endif
@endcan

@can('fill-form')
    @if ($form->json)
        <a class="btn  btn-sm small btn-primary edit_form cust_btn" href="{{ route('forms.fill', $form->id) }}" title="{{ __('Fill Form') }}"
            id="edit-form" data-actions="form/{{ $form->id }}/fill"><i class="ti ti-list"></i></a>
    @endif
@endcan
@can('duplicate-form')
    <a href="#" class="btn btn-sm small btn-success" data-toggle="tooltip" data-original-title="{{ __('Duplicate') }}"
        onclick="document.getElementById('duplicate-form-{{ $form->id }}').submit();"><i class="ti ti-squares-diagonal"></i></a>
@endcan

@can('edit-form')
    <a class="btn btn-sm small btn-primary edit_form cust_btn" href="{{ route('forms.design', $form->id) }}" id="edit-form"
        data-actions="form/{{ $form->id }}/design"><i class="ti ti-brush"></i></a>
@endcan

@can('edit-form')
    <a class="btn btn-sm small btn-info edit_form cust_btn" href="{{ route('forms.edit', $form->id) }}" id="edit-form"
        data-actions="form/{{ $form->id }}/edit"><i class="ti ti-edit"></i></a>
@endcan

@can('delete-form')
{!! Form::open(['method' => 'DELETE', 'route' => ['forms.destroy', $form->id], 'id' => 'delete-form-' . $form->id,'class'=>'d-inline']) !!}
    <a href="#" class="btn btn-sm small btn-danger show_confirm" id="delete-form-{{ $form->id }}"><i class="ti ti-trash mr-0"></i></a>
{!! Form::close() !!}
@endcan

@can('duplicate-form')
    {!! Form::open(['method' => 'POST', 'route' => ['forms.duplicate'], 'id' => 'duplicate-form-' . $form->id]) !!}
    <input type="hidden" value="{{ $form->id }}" name="form_id">
    {!! Form::close() !!}
@endcan

resources/views/form/design.blade.php
@extends('layouts.main')
@section('title', __('Form'))
@section('breadcrumb')
    <div class="col-md-12">
        <div class="page-header-title">
            <h4 class="m-b-10">{{ __('Design Forms') }}</h4>
        </div>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('Dashboard') }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('forms.index') }}">{{ __('Form') }}</a></li>
            <li class="breadcrumb-item"> {{ __('Design') }} </li>
        </ul>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="main-content" style="min-height: 517px;">
            <section class="section">
                <div class="section-body">
                    {{ Form::model($form, ['route' => ['forms.design.update', $form->id], 'method' => 'PUT', 'id' => 'design-form']) }}
                    <div class="row">
                        <div class="col-xl-12 order-xl-1">
                            <div class="card">
                                <div class="card-header">
                                    <h5>{{ __('Design Form') }}</h5>
                                </div>
                                <div class="card-body">
                                    <div class=" row">
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    @php
                                                        $array = json_decode($form->json);
                                                    @endphp
                                                    <ul id="tabs" class="nav nav-tabs mb-3 ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all ">
                                                        @if (!empty($form->json))
                                                            @foreach ($array as $key => $data)
                                                                <li class="nav-item ui-state-default ui-corner-top">
                                                                    <a href="#page-{{ $key + 1 }}" class="nav-link">{{ __('Page') . ($key + 1) }}</a>
                                                                </li>
                                                            @endforeach
                                                        @else
                                                            <li><a href="#page-1" >{{ __('Page') }}1</a></li>
                                                        @endif
                                                        <li id="add-page-tab"><a href="#new-page" class="nav-link">+
                                                                {{ __('Page') }}</a>
                                                        </li>
                                                    </ul>
                                                    @if (!empty($form->json))

                                                        @foreach ($array as $key => $data)
                                                            <div id="page-{{ $key + 1 }}" class="build-wrap">
                                                            </div>
                                                        @endforeach
                                                    @else
                                                        <div id="page-1" class="build-wrap"></div>
                                                    @endif

                                                    <div id="new-page"></div>
                                                    <input type="hidden" name="json" value="{{ $form->json }}">
                                                    <br>
                                                    <div class="action-buttons">
                                                        <button id="showData" class="d-none"
                                                            type="button">{{ __('Show Data') }}</button>
                                                        <button id="clearFields" class="d-none"
                                                            type="button">{{ __('Clear All Fields') }}</button>
                                                        <button id="getData" class="d-none"
                                                            type="button">{{ __('Get Data') }}</button>
                                                        <button id="getXML" class="d-none"
                                                            type="button">{{ __('Get XML Data') }}</button>
                                                        <button id="getJSON" class="btn btn-primary"
                                                            type="button">{{ __('Update') }}</button>
                                                        <button id="getJSONs" class="d-none"
                                                            onClick="javascript:history.go(-1)"
                                                            type="button">{{ __('Back') }}</button>
                                                        <button id="getJS" class="d-none"
                                                            type="button">{{ __('Get JS Data') }}</button>
                                                        <button id="setData" class="d-none"
                                                            type="button">{{ __('Set Data') }}</button>
                                                        <button id="addField" class="d-none"
                                                            type="button">{{ __('Add Field') }}</button>
                                                        <button id="removeField" class="d-none"
                                                            type="button">{{ __('Remove Field') }}</button>
                                                        <button id="testSubmit" class="d-none"
                                                            type="submit">{{ __('Test Submit') }}</button>
                                                        <button id="resetDemo" class="d-none"
                                                            type="button">{{ __('Reset Demo') }}</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </section>
        </div>
    </div>

@endsection
@push('style')
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/jqueryform/css/demo.css') }}">
    <link href="{{ asset('vendor/jqueryform/css/jquery.rateyo.min.css') }}" rel="stylesheet" />
    {{-- <link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" /> --}}
    <link rel="stylesheet" href="{{asset('assets/css/jquery-ui.css')}}">
@endpush
@push('script')
    <script>
        var lang = '{{ app()->getLocale() }}';
        var lang_other = '{{ __('Other') }}';
        var lang_other_placeholder = '{{ __('Enter Please') }}';
        var lang_Page = '{{ __('Page') }}';
        var lang_Custom_Autocomplete = '{{ __('Custom Autocomplete') }}';
    </script>
    <script src="{{ asset('vendor/jqueryform/js/vendor.js') }}"></script>
    <script src="{{ asset('vendor/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="{{ asset('vendor/jqueryform/js/form-builder.min.js') }}"></script>
    <script src="{{ asset('vendor/jqueryform/js/form-render.min.js') }}"></script>
    <script src="{{ asset('vendor/jqueryform/js/demoFirst.js') }}"></script>
    <script src="{{ asset('vendor/jqueryform/js/jquery.rateyo.min.js') }}"></script>
@endpush

resources/views/form/form_response.blade.php
@extends('layouts.form')
@section('title', __('Response'))
@section('content')
    <div class="section-body">
        <div class="row mx-0">
            <div class="col-6 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h4 class="text-center w-100">{{ $form->title }}</h4>
                    </div>
                    <div class="card-body">
                        @if (!empty($form->logo))
                            <div class="text-center">
                                <img id="app-dark-logo"
                                    class="img img-responsive my-5 w-30 justify-content-center text-center"
                                    src="{{ asset('storage/app/' . $form->logo) }}" alt="form_logo">
                            </div>
                        @endif
                        <h2 class="text-center w-100">{{ $form->success_msg }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/form/index.blade.php
@extends('layouts.main')
@section('title', __('Forms'))
@section('breadcrumb')
    <div class="col-md-12">
        <div class="page-header-title">
            <h4 class="m-b-10">{{ __('Forms') }}</h4>
        </div>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('Dashboard') }}</a></li>
            <li class="breadcrumb-item"> {{ __('Forms') }} </li>
        </ul>
    </div>
@endsection
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <table class="table-responsive py-5 pb-4">
                        <div class="container-fluid">
                            {{ $dataTable->table(['width' => '100%']) }}
                        </div>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('style')
    @include('layouts.includes.datatable_css')
@endpush
@push('script')
    @include('layouts.includes.datatable_js')
    {{ $dataTable->scripts() }}
    <script>
        function copyToClipboard(element) {
            var $temp = $("<input>");
            $("body").append($temp);
            $temp.val($(element).data('url')).select();
            document.execCommand("copy");
            $temp.remove();
            notifier.show('Great!', '{{ __('Copied!') }}', 'success',
                '{{ asset('assets/images/notification/ok-48.png') }}', 4000);
        }
    </script>
@endpush