routes/web.php
<?php

use App\Http\Controllers\FormController;
use App\Http\Controllers\FormValueController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SocialLoginController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test-mail', [SettingsController::class, 'testMail'])->name('test.mail')->middleware(['auth', 'xss']);
Auth::routes();

Route::group(['middleware' => ['auth', 'xss']], function () {
    Route::resource('profile', \App\Http\Controllers\ProfileController::class);
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('permission', \App\Http\Controllers\PermissionController::class);
    Route::resource('roles', \App\Http\Controllers\RoleController::class);
    Route::resource('module', \App\Http\Controllers\ModuleController::class);
    Route::resource('formvalues', \App\Http\Controllers\FormValueController::class);
});
Route::resource('forms', \App\Http\Controllers\FormController::class)->middleware(['auth', 'xss']);

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware(['auth', 'xss']);
Route::post('/chart', [HomeController::class, 'formchart'])->name('get.chart.data')->middleware(['auth', 'xss']);

Route::get('/invisible', fn () => view('invisible'));
Route::post('/invisible', function (Request $request) {
    $request->validate([
        'g-recaptcha-response' => 'required|captcha',
    ]);

    return 'Data is valid';
});

Route::get('/form-values/{id}/download/pdf', ['as' => 'download.form.values.pdf', 'uses' => '\App\Http\Controllers\FormValueController@download_pdf'])->middleware(['auth', 'xss']);

Route::get('update-avatar/{id}', [
    'as' => 'update-avatar',
    'uses' => '\App\Http\Controllers\ProfileController@showAvatar',
])->middleware(['auth', 'xss']);

Route::get('design/{id}', [
    'as' => 'forms.design',
    'uses' => '\App\Http\Controllers\FormController@design',
])->middleware(['auth', 'xss']);
// Route::get('test_design/{id}', [
//     'as' => 'forms.design',
//     'uses' => '\App\Http\Controllers\FormController@designtest'
// ])->middleware(['auth', 'xss']);
Route::put('/forms/design/{id}', ['as' => 'forms.design.update', 'uses' => '\App\Http\Controllers\FormController@designUpdate'])->middleware(['auth', 'xss']);

Route::post('update-avatar/{id}', '\App\Http\Controllers\ProfileController@updateAvatar');

Route::post('update-profile-login/{id}', [
    'uses' => '\App\Http\Controllers\ProfileController@updateLogin',
    'as' => 'update-login',
]);
Route::get('account-status/{id}', '\App\Http\Controllers\UserController@accountStatus')->name('account.status');
Route::get('profile-status', '\App\Http\Controllers\ProfileController@profileStatus')->name('profile.status');

Route::get('/forms/fill/{id}', ['as' => 'forms.fill', 'uses' => '\App\Http\Controllers\FormController@fill'])->middleware(['auth', 'xss']);
Route::get('/forms/survey/{id}', ['as' => 'forms.survey', 'uses' => '\App\Http\Controllers\FormController@publicFill'])->middleware(['xss']);
Route::put('/forms/fill/{id}', ['as' => 'forms.fill.store', 'uses' => '\App\Http\Controllers\FormController@fillStore'])->middleware(['xss']);
Route::get('/form-values/{id}/edit', ['as' => 'edit.form.values', 'uses' => '\App\Http\Controllers\FormValueController@edit'])->middleware(['auth', 'xss']);
Route::get('/form-values/{id}/view', ['as' => 'view.form.values', 'uses' => '\App\Http\Controllers\FormValueController@showSubmitedForms'])->middleware(['auth', 'xss']);
Route::post('/form-duplicate', ['as' => 'forms.duplicate', 'uses' => '\App\Http\Controllers\FormController@duplicate'])->middleware(['auth', 'xss']);
Route::get('/form-values/{id}/download/csv2', ['as' => 'download.form.values.csv2', 'uses' => '\App\Http\Controllers\FormValueController@download_csv_2'])->middleware(['auth', 'xss']);

Route::post('/mass/export/xlsx', ['as' => 'mass.export.xlsx', 'uses' => '\App\Http\Controllers\FormValueController@export_xlsx'])->middleware(['auth', 'xss']);
Route::post('/mass/export/csv', ['as' => 'mass.export.csv', 'uses' => '\App\Http\Controllers\FormValueController@export'])->middleware(['auth', 'xss']);

Route::post('ckeditors/upload', [FormController::class, 'ckupload'])->name('ckeditors.upload')->middleware('auth');

Route::resource('role', \App\Http\Controllers\RoleController::class);
Route::post('/role-permission/{id}', [
    'as' => 'roles_permit',
    'uses' => '\App\Http\Controllers\RoleController@assignPermission',
]);

Route::get('/settings', [SettingsController::class, 'index'])->name('settings')->middleware(['auth', 'xss']);

Route::post('settings/app-name/update', [
    'as' => 'settings/app-name/update',
    'uses' => '\App\Http\Controllers\SettingsController@appNameUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/app-logo/update', [
    'as' => 'settings/app-logo/update',
    'uses' => '\App\Http\Controllers\SettingsController@appLogoUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/pusher-setting/update', [
    'as' => 'settings/pusher-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@pusherSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/wasabi-setting/update', [
    'as' => 'settings/wasabi-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@wasabiSettingUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/captcha-setting/update', [
    'as' => 'settings/captcha-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@captchaSettingUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/stripe-setting/update', [SettingsController::class, 'paymentSettingUpdate'])->name('settings/stripe-setting/update');
Route::post('settings/social-setting/update', [SettingsController::class, 'socialSettingUpdate'])->name('settings/social-setting/update');

Route::get('/redirect/{provider}', [SocialLoginController::class, 'redirect']);
Route::get('/callback/{provider}', [SocialLoginController::class, 'callback'])->name('social.callback');

Route::post('filter-chart/{id}', [FormValueController::class, 'getGraphData'])->name('filter_chart')->middleware(['auth', 'xss']);

Route::post('settings/email-setting/update', [
    'as' => 'settings/email-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@emailSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/auth-settings/update', [
    'as' => 'settings/auth-settings/update',
    'uses' => '\App\Http\Controllers\SettingsController@authSettingsUpdate',
])->middleware(['auth', 'xss']);

Route::post('test-mail', '\App\Http\Controllers\SettingsController@testSendMail')->name('test.send.mail')->middleware(['auth', 'xss']);
Route::post('/verify-2fa', [
    'as' => 'verify-2fa',
    'uses' => '\App\Http\Controllers\ProfileController@verify',
]);

Route::post('/activate-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@activate',
    'as' => 'activate-2fa',
]);

Route::post('/enable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@enable',
    'as' => 'enable-2fa',
]);

Route::post('/disable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@disable',
    'as' => 'disable-2fa',
]);

Route::get('/2fa/instruction', [
    'uses' => '\App\Http\Controllers\ProfileController@instruction',
]);

Route::post('/2fa', fn () => redirect()->to(URL()->previous()))->name('2fa')->middleware('2fa');

Route::group(['prefix' => '2fa'], function () {
    Route::get('/', '\App\Http\Controllers\LoginSecurityController@show2faForm');
    Route::post('/generateSecret', '\App\Http\Controllers\LoginSecurityController@generate2faSecret')->name('generate2faSecret');
    Route::post('/enable2fa', '\App\Http\Controllers\LoginSecurityController@enable2fa')->name('enable2fa');
    Route::post('/disable2fa', '\App\Http\Controllers\LoginSecurityController@disable2fa')->name('disable2fa');

    Route::post('/2faVerify', fn () => redirect()->to(URL()->previous()))->name('2faVerify')->middleware('2fa');
});

Route::get('/test_middleware', fn () => '2FA middleware work!')->middleware(['auth', '2fa']);

Route::any('(:any)/(:all?)', function ($first, $rest = '') {
    $page = $rest ? "{$first}/{$rest}" : $first;
    dd($page);
});

Route::get('setting/{id}', [
    'as' => 'setting',
    'uses' => '\App\Http\Controllers\SettingsController@loadsetting',
])->middleware(['auth', 'xss']);

Route::post('ckeditor/upload', '\App\Http\Controllers\FormController@upload')->name('ckeditor.upload');
Route::group(
    ['middleware' => ['auth', 'xss']],
    function () {
        Route::get('change-language/{lang}', '\App\Http\Controllers\LanguageController@changeLanquage')->name('change.language');
        Route::get('manage-language/{lang}', '\App\Http\Controllers\LanguageController@manageLanguage')->name('manage.language');
        Route::post('store-language-data/{lang}', '\App\Http\Controllers\LanguageController@storeLanguageData')->name('store.language.data');
        Route::get('create-language', '\App\Http\Controllers\LanguageController@createLanguage')->name('create.language');
        Route::post('store-language', '\App\Http\Controllers\LanguageController@storeLanguage')->name('store.language');
        Route::delete('/lang/{lang}', '\App\Http\Controllers\LanguageController@destroyLang')->name('lang.destroy');
    }
);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"
    dir="{{ \App\Facades\UtilityFacades::getsettings('rtl') == '1' ? 'rtl' : '' }}">
<head>
    @php
        $primary_color = \App\Facades\UtilityFacades::getsettings('color');
        if (isset($primary_color)) {
            $color = $primary_color;
        } else {
            $color = 'theme-4';
        }
    @endphp
    <title>@yield('title') | {{ Utility::getsettings('app_name') }}</title>

    <!-- Meta -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Favicon icon -->
    <link rel="icon" href="{{ asset('vendor/img/favicon.png') }}" type="image/x-icon" />

    <!-- font css -->
    <link rel="stylesheet" href="{{ asset('assets/fonts/tabler-icons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/feather.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/fontawesome.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/material.css') }}">

    <!-- vendor css -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" id="main-style-link">
    <link rel="stylesheet" href="{{ asset('assets/css/customizer.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/notifier.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/select2/dist/css/select2.min.css') }}">
    @if (Utility::getsettings('rtl') == '1')
        <link rel="stylesheet" href="{{ asset('assets/css/style-rtl.css') }}" id="main-style-link">
    @else
        @if (Utility::getsettings('dark_mode') == 'on')
            <link rel="stylesheet" href="{{ asset('assets/css/style-dark.css') }}">
        @else
            <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" id="main-style-link">
        @endif
    @endif

</head>

<body class="{{ $color }}">
    <!-- [ auth-signup ] start -->
    <div class="auth-wrapper auth-v1">
        <div class="bg-auth-side bg-primary"></div>
        <div class="auth-content">

            @yield('content')

            <div class="auth-footer">
                <div class="container-fluid">
                    <div class="row" style="display: flex;align-items: center;">
                        <div class="col-6">
                            @if (Utility::getsettings('dark_mode') == 'on')
                            <img src="{{ Storage::url(setting('app_logo')) ? Storage::url('uploads/appLogo/app-logo.png') : '' }}"  class="app-logo" style="width: 24%" />
                        @else
                            <img src="{{ Utility::getsettings('app_dark_logo') ? Storage::url('uploads/appLogo/app-dark-logo.png') : '' }}"  class="app-logo" style="width: 24%" />
                        @endif
                        </div>
                        <div class="col-6 text-end">
                            &copy; {{ date('Y') }} <a href="#" class="font-weight-bold ml-1"
                                target="_blank">{{ config('app.name') }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ auth-signup ] end -->

    <!-- Required Js -->
    <script src="{{ asset('assets/js/vendor-all.js') }}"></script>
    <script src="{{ asset('assets/js/plugins/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/plugins/feather.min.js') }}"></script>
    <script>
        feather.replace();
    </script>
    <div class="pct-customizer">
        <div class="pct-c-btn">
            <button class="btn btn-primary" id="pct-toggler">
                <i data-feather="settings"></i>
            </button>
        </div>
        <div class="pct-c-content">
            <div class="pct-header bg-primary">
                <h5 class="mb-0 text-white f-w-500">Theme Customizer</h5>
            </div>
            <div class="pct-body">
                <h6 class="mt-2">
                    <i data-feather="credit-card" class="me-2"></i>Primary color settings
                </h6>
                <hr class="my-2" />
                <div class="theme-color themes-color">
                    <a href="#!" class="" data-value="theme-1"></a>
                    <a href="#!" class="" data-value="theme-2"></a>
                    <a href="#!" class="" data-value="theme-3"></a>
                    <a href="#!" class="" data-value="theme-4"></a>
                </div>

                <h6 class="mt-4">
                    <i data-feather="layout" class="me-2"></i>Sidebar settings
                </h6>
                <hr class="my-2" />
                <div class="form-check form-switch">
                    <input type="checkbox" class="form-check-input" id="cust-theme-bg" checked />
                    <label class="form-check-label f-w-600 pl-1" for="cust-theme-bg">Transparent layout</label>
                </div>

                <h6 class="mt-4">
                    <i data-feather="sun" class="me-2"></i>Layout settings
                </h6>
                <hr class="my-2" />
                <div class="form-check form-switch mt-2">
                    <input type="checkbox" class="form-check-input" id="cust-darklayout" />
                    <label class="form-check-label f-w-600 pl-1" for="cust-darklayout">Dark Layout</label>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ asset('vendor/js/jquery.min.js') }}"></script>

    <script src="{{ asset('assets/js/plugins/notifier.js') }}"></script>
    <script src="{{ asset('vendor/select2/dist/js/select2.min.js') }}"></script>
    @include('layouts.includes.alerts')
    @if (setting('rtl') == '1')
    @endif
    <script>
        @if (session('failed'))
            notifier.show('Failed!', '{{ session('failed') }}', 'danger',
            '{{ asset('assets/images/notification/high_priority-48.png') }}', 4000);
        @endif

        @if (session('errors'))
            notifier.show('Error!', '{{ session('errors') }}', 'danger',
            '{{ asset('assets/images/notification/high_priority-48.png') }}', 4000);
        @endif

        @if (session('successful'))
            notifier.show('SuccessfulLY!', '{{ session('successful') }}', 'success',
            '{{ asset('assets/images/notification/ok-48.png') }}', 4000);
        @endif

        @if (session('success'))
            notifier.show('Done!', '{{ session('success') }}', 'success',
            '{{ asset('assets/images/notification/ok-48.png') }}', 4000);
        @endif
        @if (session('warning'))
            notifier.show('Warning!', '{{ session('warning') }}', 'warning',
            '{{ asset('assets/images/notification/medium_priority-48.png') }}', 4000);
        @endif
    </script>
    <script>
        @if (session('status'))
            notifier.show('Great!', '{{ session('status') }}', 'info',
            '{{ asset('assets/images/notification/survey-48.png') }}', 4000);
        @endif
    </script>
    <script>
        $(document).on('click', '.delete-action', function() {
            var form_id = $(this).attr('data-form-id')
            $.confirm({
                title: '{{ __('Alert !') }}',
                content: '{{ __('Are You sure ?') }}',
                buttons: {
                    confirm: function() {
                        $("#" + form_id).submit();
                    },
                    cancel: function() {}
                }
            });
        });
    </script>
    @stack('script')
    <script>
        feather.replace();
        var pctoggle = document.querySelector("#pct-toggler");
        if (pctoggle) {
            pctoggle.addEventListener("click", function() {
                if (
                    !document.querySelector(".pct-customizer").classList.contains("active")
                ) {
                    document.querySelector(".pct-customizer").classList.add("active");
                } else {
                    document.querySelector(".pct-customizer").classList.remove("active");
                }
            });
        }

        var themescolors = document.querySelectorAll(".themes-color > a");
        for (var h = 0; h < themescolors.length; h++) {
            var c = themescolors[h];

            c.addEventListener("click", function(event) {
                var targetElement = event.target;
                if (targetElement.tagName == "SPAN") {
                    targetElement = targetElement.parentNode;
                }
                var temp = targetElement.getAttribute("data-value");
                removeClassByPrefix(document.querySelector("body"), "theme-");
                document.querySelector("body").classList.add(temp);
            });
        }


        function removeClassByPrefix(node, prefix) {
            for (let i = 0; i < node.classList.length; i++) {
                let value = node.classList[i];
                if (value.startsWith(prefix)) {
                    node.classList.remove(value);
                }
            }
        }
    </script>


</body>

</html>

resources/views/layouts/form.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"
    dir="{{ \App\Facades\UtilityFacades::getsettings('rtl') == '1' ? 'rtl' : '' }}">

<head>
    @php
        $primary_color = \App\Facades\UtilityFacades::getsettings('color');
        if (isset($primary_color)) {
            $color = $primary_color;
        } else {
            $color = 'theme-4';
        }
    @endphp
      <title>@yield('title') | {{ Utility::getsettings('app_name') }}</title>

  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Favicon icon -->
    <link rel="icon" href="{{ asset('vendor/img/favicon.png') }}" type="image/x-icon" />
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/notifier.css') }}">

    <!-- font css -->
    <link rel="stylesheet" href="{{ asset('assets/fonts/tabler-icons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/feather.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/fontawesome.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/material.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/css/jquery-confirm.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/jqueryform/css/jquery.rateyo.min.css') }}">

    <!-- vendor css -->
    <link rel="stylesheet" href="{{ asset('vendor/js/plugins/croppie/css/croppie.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/flatpickr.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" id="main-style-link">
    <link rel="stylesheet" href="{{ asset('assets/css/customizer.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/bootstrap-switch-button.min.css') }}">

    @if (Utility::getsettings('rtl') == '1')
        <link rel="stylesheet" href="{{ asset('assets/css/style-rtl.css') }}" id="main-style-link">
    @else
        @if (Utility::getsettings('dark_mode') == 'on')
            <link rel="stylesheet" href="{{ asset('assets/css/style-dark.css') }}">
        @else
            <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" id="main-style-link">
        @endif
    @endif
    <link rel="stylesheet" href="{{ asset('vendor/css/custom.css') }}">
    @stack('style')

</head>

<body class="{{ $color }}">
   

         
    
</body>

<div class="dash-container">
    <div class="dash-content">
        
        @yield('content')

    </div>
</div>



<script src="{{ asset('vendor/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/feather.min.js') }}"></script>
<script src="{{ asset('vendor/modules/tooltip.js') }}"></script>
<script src="{{ asset('assets/js/chart.min.js') }}"></script>
<script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('vendor/modules/chocolat/dist/js/jquery.chocolat.min.js') }}  "></script>
<script src="{{ asset('vendor/modules/select2/dist/js/select2.min.js') }}"></script>
<script src="{{ asset('vendor/js/plugins/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('vendor/js/plugins/summernote/dist/summernote-bs4.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/notifier.js') }}"></script>
<script src="{{ asset('assets/js/plugins/flatpickr.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/choices.min.js') }}"></script>
<script src="{{ asset('vendor/js/plugins/croppie/js/croppie.min.js') }}"></script>
<script src="{{ asset('vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('vendor/js/plugins/datatable/js/datatables.min.js') }}"></script>
<script src="{{ asset('vendor/js/scripts.js') }}"></script>
<script src="{{ asset('vendor/js/jquery-confirm.min.js') }}"></script>
<script src="{{ asset('vendor/js/custom.js') }}"></script>
<script src="{{asset('assets/js/plugins/sweetalert2.all.min.js') }}"></script>
<script src="{{ asset('vendor/jqueryform/js/jquery.rateyo.min.js') }}"></script>





@include('layouts.includes.alerts')
@stack('script')
</body>

</html>

resources/views/layouts/sidebar.blade.php
@php
use App\Models\Form;
$users = \Auth::user();
$currantLang = $users->currentLanguage();
$languages = Utility::languages();
$role_id = $users->roles->first()->id;
if (Auth::user()->type == 'Admin') {
    $forms = Form::all();
} else {
    $forms = Form::select(['forms.*'])
        ->leftJoin('users', 'users.id', 'forms.created_by')
        ->whereIn('forms.id', function ($query) use ($role_id) {
            $query
                ->select('form_id')
                ->from('user_forms')
                ->where('role_id', $role_id);
        })
        ->get();
}
@endphp

<nav class="dash-sidebar light-sidebar transprent-bg">
    <div class="navbar-wrapper">
        <div class="m-header">
            <a href="{{ route('home') }}" class="b-brand text-center">
                <!-- ========   change your logo hear   ============ -->
                @if (Utility::getsettings('dark_mode') == 'on')
                <img src="{{ Utility::getsettings('app_logo') ? Storage::url('uploads/appLogo/app-logo.png') : '' }}"
                class="app-logo w-75">
                @else
                <img src="{{ Utility::getsettings('app_dark_logo') ? Storage::url('uploads/appLogo/app-dark-logo.png') : '' }}"
                        class="app-logo w-75">
                @endif
            </a>
        </div>
        <div class="navbar-content">
            <ul class="dash-navbar" style="display: block;">
                <li class="dash-item dash-hasmenu {{ request()->is('/') ? 'active' : '' }}">
                    <a href="{{ route('home') }}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-home"></i></span>
                        <span class="dash-mtext custom-weight">{{ __('Dashboard') }}</span></a>
                </li>

                @can('manage-user')
                    <li class="dash-item dash-hasmenu">
                        <a class="dash-link" href="{{ route('users.index') }}"><span class="dash-micon">
                                <i class="ti ti-user"></i></span>
                            <span class="dash-mtext">{{ __('Users') }}</span>
                        </a>
                    </li>
                @endcan
                @can('manage-role')
                    <li class="dash-item dash-hasmenu {{ request()->is('roles*') ? 'active' : '' }}">
                        <a class="dash-link" href="{{ route('roles.index') }}"><span class="dash-micon">
                                <i class="ti ti-key"></i></span>
                            <span class="dash-mtext">{{ __('Roles') }}</span>
                        </a>
                    </li>
                @endcan
                @can('manage-setting')
                    <li class="dash-item dash-hasmenu">
                        <a class="dash-link" href="{{ route('settings') }}"><span class="dash-micon">
                                <i class="ti ti-settings"></i></span>
                            <span class="dash-mtext">{{ __('Settings') }}</span>
                        </a>
                    </li>
                @endcan
                @can('manage-form')
                    <li class="dash-item dash-hasmenu {{ request()->is('forms*','design*') ? 'active' : '' }}">
                        <a class="dash-link" href="{{ route('forms.index') }}"><span class="dash-micon">
                                <i class="ti ti-forms"></i></span>
                            <span class="dash-mtext">{{ __('Forms') }}</span>
                        </a>
                    </li>
                @endcan
                @can('manage-submitted-form')

                    <li class="dash-item dash-hasmenu {{ request()->is('formvalues*') ? 'active' : '' }}">
                        <a href="#" class="dash-link"><span class="dash-micon"><i
                                    class="ti ti-list"></i></span><span
                                class="dash-mtext">{{ __('Submitted Forms') }}</span><span class="dash-arrow"><i
                                    data-feather="chevron-right"></i></span></a>
                        <ul
                            class="dash-submenu {{ Request::route()->getName() == 'view.form.values' ? 'd-block' : '' }}">
                            @foreach ($forms as $form)
                                <li class="dash-item">
                                    <a class="dash-link {{ Request::route()->getName() == 'view.form.values' ? 'show' : '' }}"
                                        href="{{ route('view.form.values', $form->id) }}">{{ $form->title }}</a>
                                </li>
                            @endforeach
                        </ul>
                    </li>
                @endcan
                @can('manage-chat')
                    @if (setting('pusher_status') == '1')
                        <li class="dash-item dash-hasmenu {{ request()->is('chat*') ? 'active' : '' }}">

                            <a class="dash-link" href="{{ route('chat') }}"><span class="dash-micon">
                                    <i class="ti ti-brand-hipchat"></i></span>
                                <span class="dash-mtext">{{ __('Chat') }}</span>
                            </a>
                        </li>
                    @endif
                @endcan
                @can('manage-language')
                    <li class="dash-item dash-hasmenu {{ request()->is('lang*') ? 'active' : '' }}">
                        <a class="dash-link" href="{{ route('manage.language', [$currantLang]) }}"><span
                                class="dash-micon">
                                <i class="ti ti-world"></i></span>
                            <span class="dash-mtext">{{ __('Manage Language') }}</span>
                        </a>
                    </li>
                @endcan
            </ul>

        </div>
</nav>